[project]
name = "heidi-eval-runner-cloud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prefect-aws>=0.7.1",
    "prefect[kubernetes]>=3.6.1",
]
